baseurl = "http://esolia.pro/"
title = "eSolia Inc. Pro Blog"
contentdir = "content/"
publishdir = "public/"
canonifyurls = "false"
copyright = "This work is copyright. All rights reserved by eSolia Inc."
MetaDataFormat = "yaml"
# For RSS only, apparently
languageCode = "en-US"

[author]
    name = "eSolia Inc."

[permalinks]
    # Optional. Change the permalink format for the 'post' content type.
    # The format shown here is the same one Jekyll/Octopress uses by default.
    post = "/:section/:slug"

[taxonomies]
    tag = "tags"
    topic = "topics"
    series = "series"

[blackfriday]
    plainIdAnchors = true

[params]
    locale = "en-US"
    alternatelocales = ["ja-JP"]
    description = "Blog site of eSolia Inc. - a Tokyo-based IT Management and support firm."
    keywords = ["Blog","Japan","ICT","IT","Tokyo","Greater Tokyo","Kanto","IT","Management","Support","Outsourcing","Helpdesk","Website","Project Management","Consulting","Development","Operations"]
    author = "Team eSolia"
    accountableperson = "Rick Cogley"
    entityname = "eSolia Inc."
    # Used when a given page doesn't set its own.
    defaultDescription = "Content by eSolia Inc."
    defaultKeywords = "eSolia"
    ISO8601 = "2006-01-02T15:04:05JST"
    googleAnalytics = "UA-1040233-7"
    discourseURL = "http://discourse.esolia.pro"

[[menu.sideen]]
    name = "eSolia Inc"
    identifier = "esoliaen"
    weight = 1

[[menu.sideen]]
    name = "About eSolia"
    identifier = "aboutesolia"
    url = "http://esolia.com/about"
    post = "_blank"
    parent = "esoliaen"
    weight = 10

[[menu.sideen]]
    name = "eSolia Services"
    identifier = "ourservices"
    weight = 20
    url = "http://esolia.com/topics/services"
    post = "_blank"
    parent = "esoliaen"

[[menu.sideen]]
    name = "Posts"
    identifier = "posts"
    weight = 5

[[menu.sideen]]
    name = "English"
    identifier = "english"
    url = "/en"
    parent = "posts"
    weight = 10

[[menu.sideen]]
    name = "日本語"
    identifier = "japanese"
    url = "/ja"
    parent = "posts"
    weight = 20

[[menu.sideen]]
    name = "Topics"
    identifier = "topics"
    weight = 111

[[menu.sideen]]
    name = "All Topics"
    identifier = "alltopics"
    url = "/topics"
    parent = "topics"
    weight = 1

[[menu.sideen]]
    name = "All Tags"
    identifier = "alltags"
    url = "/tags"
    parent = "topics"
    weight = 2

[[menu.sideen]]
    name = "Tools"
    identifier = "tools"
    weight = 222

[[menu.sideen]]
    name = "Zerobin"
    identifier = "zerobin"
    url = "https://zerobin.esolia.com"
    post = "_blank"
    parent = "tools"
    weight = 22

[[menu.sideen]]
    name = "eSolia Connect"
    identifier = "connect"
    url = "http://connect.esolia.com"
    post = "_blank"
    parent = "tools"
    weight = 33

[[menu.sideja]]
    name = "株式会社イソリア"
    identifier = "esoliaja"
    weight = 1

[[menu.sideja]]
    name = "イソリアについて"
    identifier = "aboutesoliaja"
    url = "http://esolia.co.jp/about"
    post = "_blank"
    parent = "esoliaja"
    weight = 10

[[menu.sideja]]
    name = "イソリア サービス"
    identifier = "ourservicesja"
    weight = 20
    url = "http://esolia.co.jp/topics/サービス"
    post = "_blank"
    parent = "esoliaja"

[[menu.sideja]]
    name = "ポスト"
    identifier = "postsja"
    weight = 5

[[menu.sideja]]
    name = "English"
    identifier = "englishja"
    url = "/en"
    parent = "postsja"
    weight = 10

[[menu.sideja]]
    name = "日本語"
    identifier = "japaneseja"
    url = "/ja"
    parent = "postsja"
    weight = 20

[[menu.sideja]]
    name = "トピック"
    identifier = "topicsja"
    weight = 111

[[menu.sideja]]
    name = "全トピック"
    identifier = "alltopicsja"
    url = "/topics"
    parent = "topicsja"
    weight = 1

[[menu.sideja]]
    name = "全タグ"
    identifier = "alltagsja"
    url = "/tags"
    parent = "topicsja"
    weight = 2

[[menu.sideja]]
    name = "便利ツール"
    identifier = "toolsja"
    weight = 222

[[menu.sideja]]
    name = "ゼロビン"
    identifier = "zerobinja"
    url = "https://zerobin.esolia.com"
    post = "_blank"
    parent = "toolsja"
    weight = 22

[[menu.sideja]]
    name = "イソリア コネクト"
    identifier = "connectja"
    url = "http://connect.esolia.com"
    post = "_blank"
    parent = "toolsja"
    weight = 33

[[menu.detailfooter1]]
    name = "All Topics"
    identifier = "topics"
    url = "/topics"
    weight = 55

[[menu.homefooter3]]
    name = "Zerobin"
    identifier = "zerobin"
    url = "https://zerobin.esolia.com"
    post = "_blank"
    weight = 22

[[menu.homefooter3]]
    name = "eSolia Connect"
    identifier = "connect"
    url = "http://connect.esolia.com"
    post = "_blank"
    weight = 33

[[menu.homefooter3]]
    name = "All Topics"
    identifier = "topics"
    url = "/topics"
    weight = 44

[[menu.homefooter3]]
    name = "All Tags"
    identifier = "tags"
    url = "/tags"
    weight = 55

[[menu.homefooter1]]
    name = "eSolia Main"
    identifier = "esoliamain"
    url = "http://esolia.com"
    post = "_blank"
    weight = 10

[[menu.homefooter1]]
    name = "About eSolia"
    identifier = "aboutesolia"
    url = "http://esolia.com/about"
    post = "_blank"
    weight = 20

[[menu.homefooter1]]
    name = "Message"
    identifier = "esoliamessage"
    url = "http://esolia.com/message-from-esolia"
    post = "_blank"
    weight = 30

[[menu.homefooter1]]
    name = "Info Request"
    identifier = "esoliainforequest"
    url = "http://esolia.com/info-request"
    post = "_blank"
    weight = 40

[[menu.homefooter2]]
    name = "イソリア メイン"
    identifier = "esoliamain"
    url = "http://esolia.co.jp"
    post = "_blank"
    weight = 10

[[menu.homefooter2]]
    name = "イソリアについて"
    identifier = "aboutesolia"
    url = "http://esolia.co.jp/about"
    post = "_blank"
    weight = 20

[[menu.homefooter2]]
    name = "メッセージ"
    identifier = "esoliamessage"
    url = "http://esolia.co.jp/message-from-esolia"
    post = "_blank"
    weight = 30

[[menu.homefooter2]]
    name = "お問い合わせ"
    identifier = "esoliainforequest"
    url = "http://esolia.co.jp/info-request"
    post = "_blank"
    weight = 40

[[menu.homefooter4]]
    name = "ゼロビン"
    identifier = "zerobin"
    url = "https://zerobin.esolia.com/?language=jp"
    post = "_blank"
    weight = 22

[[menu.homefooter4]]
    name = "イソリア コネクト"
    identifier = "connect"
    url = "http://connect.esolia.com"
    post = "_blank"
    weight = 33

[[menu.homefooter4]]
    name = "全てのトピック一覧"
    identifier = "topics"
    url = "/topics"
    weight = 44

[[menu.homefooter4]]
    name = "全てのタブ一覧"
    identifier = "tags"
    url = "/tags"
    weight = 55
